version: '2.3'
services:
  wso2ei-mysql:
    image: mysql:5.7.20
    container_name: wso2ei-mysql
    hostname: wso2ei-mysql
    ports:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      # mounting MySQL init scripts
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      # mounting MySQL DB data
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  wso2ei-analytics:
    image: wso2ei-analytics:6.3.0
    container_name: wso2ei-analytics
    hostname: wso2ei-analytics
    ports:
      - 9444:9444
      - 9612:9612
      - 9712:9712
      - 7612:7612
      - 7712:7712
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:9444/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    volumes:
      # mounting configurations
      - ./analytics:/home/wso2carbon/wso2-config-volume/
    depends_on:
      wso2ei-mysql:
        condition: service_healthy
    links:
      - wso2ei-mysql
  wso2ei-integrator:
    image: wso2ei-integrator:6.3.0
    container_name: wso2ei-integrator
    hostname: wso2ei-integrator
    ports:
      - 9443:9443
      - 8243:8243
      - 8280:8280
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:9443/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s
    volumes:
      # mounting configurations
      - ./integrator:/home/wso2carbon/wso2-config-volume/
    depends_on:
      wso2ei-mysql:
        condition: service_healthy
      wso2ei-analytics:
        condition: service_healthy
    links:
      - wso2ei-mysql
      - wso2ei-analytics
